import { getDB } from "@/lib/datasource";
import { Example } from "@/entities/Example";
import PredictionDemo from "./PredictionDemo";

export default async function Home() {
  const db = await getDB();
  const items = await db.getRepository(Example).find();

  return (
    <main>
      <h1>Hackathon</h1>

      <section>
        <h2>Pre-computed Predictions</h2>
        <p className="description">
          These predictions were generated by the Data Scientist, loaded into the database by the Data Engineer, and queried by the app on page load.
        </p>
        <ul>
          {items.map((item) => (
            <li key={item.id}>
              {item.name}: {item.score}
            </li>
          ))}
        </ul>
      </section>

      <section>
        <h2>Live ONNX Prediction</h2>
        <p className="description">
          This prediction runs a trained ML model in real-time. The model was exported by the Data Scientist as an ONNX file and loaded by the app on demand.
        </p>
        <PredictionDemo />
      </section>
    </main>
  );
}
